[workspace]
resolver = "3"

members = [
    "relaxng-syntax",
    "relaxng-model",
    "relaxng-validator",
    "relaxng-tool",
    "relaxng-gen",
]

[profile.release]
debug = true

[profile.bench]
# for profiling,
debug = true

